name: apibuild

on:
    push:
        paths:
            - ".github/workflows/apibuild.yml"
            - "api/**"
    workflow_dispatch:  # manual trigger

jobs:
    build:
        name: build-api
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: dotnet --list-runtimes
            - run: dotnet --list-sdks
            - run: dotnet build
              working-directory: ./api
