name: appupperbuild

on:
    push:
        paths:
            - ".github/workflows/appupperbuild.yml"
            - "upper/**"
    workflow_dispatch:  # manual trigger
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: pwd && ls -al
            - uses: actions/checkout@v4
            - run: pwd && ls -al
            - uses: actions/setup-go@v2
              with:
                  go-version: '1.22'
            - run: cd upper && go build
            - run: cd upper && go test

        