name: appupperbuild

on:
    push:
        paths:
            - ".github/workflows/appupperbuild.yml"
            - "upper/**"
    workflow_dispatch:  # manual trigger
jobs:
    build:
        runs-on: ubuntu-22.04
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - run: gh auth status 
            - run: gh workflow list
            - run: pwd && ls -al

            
            
        