name: appupperbuild

on:
    push:
        paths:
            - ".github/workflows/appupperbuild.yml"
            - "upper/**"
    workflow_dispatch:  # manual trigger
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: pwd && ls -al
            - uses: actions/checkout@v4
            - run: pwd && ls -al
            - uses: actions/setup-go@v5
              with:
                #   go-version: '1.23'
                go-version-file: upper/go.mod
                cache-dependency-path: upper/go.sum
            - run: |
                ls -l
                go build 
                go test -v
                ls -l
                cat go.mod
              working-directory: upper
            
            
        