name: cdpipelineaws

on:
    push:
        paths:
            - ".github/workflows/cdpipelineaws.yml"
            - "api/**"
    workflow_dispatch:  # manual trigger
permissions:
    contents: read
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
             fetch-depth: 0 # all commits are fetched
          - uses: docker/setup-buildx-action@v3
          - run: docker buildx ls
          - uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
          - run: ./build-push.sh # can reuse local build scripts for CI/CD.
            working-directory: api
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: production
        steps:
         - name: Configure AWS Credentials to Personal AWS Account  
           uses: aws-actions/configure-aws-credentials@v4
           with:
            role-to-assume: arn:aws:iam::897722668989:role/githubactionrole
            aws-region: us-east-1
            role-session-name: githubactionsession
         - run: |
             aws sts get-caller-identity
