name: upper-image 

on:
    push:
        paths:
            - ".github/workflows/upperimage.yml"
            - "upper/**"
    workflow_dispatch:  # manual trigger
permissions:
    packages: write
    contents: read
jobs:
    image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker version
            - run: docker build -t upper .
              working-directory: upper
            - name: test image
              run: docker container run upper hello Ren
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - run: docker tag upper ghcr.io/ren4u/upper:latest
            - run: docker tag upper ghcr.io/ren4u/upper:${{ github.ref_name }}
            - run: docker push ghcr.io/ren4u/upper:latest
            - run: docker push ghcr.io/ren4u/upper:${{ github.ref_name }}

            
            
            
